export const coursesDUT = [
    // Faculty of Accounting and Informatics
    { id: 'dut-1', title: 'Bachelor of Information and Communications Technology', requirements: { minAPS: null, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'mathematics', minLevel: 4 }] } },
    { id: 'dut-2', title: 'Bachelor of ICT: Internet of Things (IoT)', requirements: { minAPS: null, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'mathematics', minLevel: 4 }, { subject: 'physical_sciences', minLevel: 4 }] } },
    { id: 'dut-3', title: 'Diploma ICT: Applications Development', requirements: { minAPS: null, requiredSubjects: [{ subject: 'english', minLevel: 3 }, { subject: 'mathematics', minLevel: 3 }] } },
    { id: 'dut-4', title: 'Diploma ICT: Business Analysis', requirements: { minAPS: null, requiredSubjects: [{ subject: 'english', minLevel: 3 }, { subject: 'mathematics', minLevel: 3 }] } },
    { id: 'dut-5', title: 'Diploma Business & Information Management', requirements: { minAPS: null, requiredSubjects: [{ subject: 'english', minLevel: 3 }, { subject: 'mathematics', minLevel: 3 }] } },
    { id: 'dut-6', title: 'Diploma in Accounting', requirements: { minAPS: null, requiredSubjects: [{ subject: 'english', minLevel: 3 }, { subject: 'mathematics', minLevel: 3 }] } },
    { id: 'dut-7', title: 'Diploma in Internal Auditing', requirements: { minAPS: null, requiredSubjects: [{ subject: 'english', minLevel: 3 }, { subject: 'mathematics', minLevel: 4 }] } },
    { id: 'dut-8', title: 'Diploma in Library and Information Studies', requirements: { minAPS: null, requiredSubjects: [{ subject: 'english', minLevel: 3 }, { subject: 'mathematics', minLevel: 3 }] } },
    { id: 'dut-9', title: 'Diploma in Management Accounting', requirements: { minAPS: null, requiredSubjects: [{ subject: 'english', minLevel: 3 }, { subject: 'mathematics', minLevel: 3 }] } },
    { id: 'dut-10', title: 'Diploma in Taxation', requirements: { minAPS: null, requiredSubjects: [{ subject: 'english', minLevel: 3 }, { subject: 'mathematics', minLevel: 3 }] } },

    // Faculty of Applied Sciences
    { id: 'dut-11', title: 'Bachelor of Applied Science in Biotechnology', requirements: { minAPS: 28, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'mathematics', minLevel: 4 }, { subject: 'life_sciences', minLevel: 4 }, { subject: 'physical_sciences', minLevel: 4 }] } },
    { id: 'dut-12', title: 'Bachelor of Applied Science in Food Science and Technology', requirements: { minAPS: 28, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'mathematics', minLevel: 4 }, { subject: 'life_sciences', minLevel: 4 }, { subject: 'physical_sciences', minLevel: 4 }] } },
    { id: 'dut-13', title: 'Bachelor of Applied Science in Industrial Chemistry', requirements: { minAPS: null, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'mathematics', minLevel: 4 }, { subject: 'physical_sciences', minLevel: 4 }] } },
    { id: 'dut-14', title: 'Bachelor of Applied Science in Textile Science', requirements: { minAPS: null, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'mathematics', minLevel: 4 }, { subject: 'physical_sciences', minLevel: 4 }] } },
    { id: 'dut-15', title: 'Bachelor of Sport Science and Management', requirements: { minAPS: 28, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'mathematics', minLevel: 4 }, { subject: 'life_sciences', minLevel: 4 }] } },
    { id: 'dut-16', title: 'Diploma in Shipping & Logistics', requirements: { minAPS: null, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'mathematics', minLevel: 3 }] } },
    { id: 'dut-17', title: 'Diploma in Analytical Chemistry', requirements: { minAPS: null, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'mathematics', minLevel: 4 }, { subject: 'physical_sciences', minLevel: 3 }] } },
    { id: 'dut-18', title: 'Diploma in Clothing Management', requirements: { minAPS: null, requiredSubjects: [{ subject: 'english', minLevel: 3 }] } },
    { id: 'dut-19', title: 'Diploma in Consumer Sciences in Food and Nutrition', requirements: { minAPS: null, requiredSubjects: [{ subject: 'english', minLevel: 3 }, { subject: 'mathematics', minLevel: 3 }] } },
    { id: 'dut-20', title: 'Diploma in Nautical Science', requirements: { minAPS: null, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'mathematics', minLevel: 4 }, { subject: 'physical_sciences', minLevel: 4 }] } },
    { id: 'dut-21', title: 'Diploma in Sustainable Horticulture and Landscaping', requirements: { minAPS: null, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'mathematics', minLevel: 3 }, { subject: 'life_sciences', minLevel: 4 }] } },
    { id: 'dut-22', title: 'Higher Cert Sport Management Science', requirements: { minAPS: 24, requiredSubjects: [{ subject: 'english', minLevel: 3 }] } },
    { id: 'dut-23', title: 'Higher Certificate: Applied Sciences', requirements: { minAPS: null, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'mathematics', minLevel: 3 }] } },

    // Faculty of Arts and Design
    { id: 'dut-24', title: 'Bachelor of Applied Arts in Commercial Photography', requirements: { minAPS: null, requiredSubjects: [{ subject: 'english', minLevel: 3 }] } },
    { id: 'dut-25', title: 'Bachelor of Applied Arts in Screen Arts and Technology', requirements: { minAPS: 36, requiredSubjects: [{ subject: 'english', minLevel: 4 }] } },
    { id: 'dut-26', title: 'Bachelor of Design in Visual Communication Design', requirements: { minAPS: null, requiredSubjects: [{ subject: 'english', minLevel: 3 }] } },
    { id: 'dut-27', title: 'Bachelor of Education in Senior Phase & FET Teaching: Economic and Management Sciences', requirements: { minAPS: 28, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'accounting', minLevel: 4 }] } },
    { id: 'dut-28', title: 'Bachelor of Education in Senior Phase & FET Teaching: Electrical Technology', requirements: { minAPS: 28, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'mathematics', minLevel: 4 }] } },
    { id: 'dut-29', title: 'Bachelor of Education in Senior Phase & FET Teaching: Mechanical Technology', requirements: { minAPS: 28, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'mathematics', minLevel: 4 }] } },
    { id: 'dut-30', title: 'Bachelor of Education in Senior Phase & FET Teaching: Languages', requirements: { minAPS: 28, requiredSubjects: [{ subject: 'english', minLevel: 5 }] } },
    { id: 'dut-31', title: 'Bachelor of Education in Senior Phase & FET Teaching: Natural Sciences', requirements: { minAPS: 28, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'mathematics', minLevel: 4 }] } },
    { id: 'dut-32', title: 'Bachelor of Education in Senior Phase & FET Teaching: Civil Technology', requirements: { minAPS: 28, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'mathematics', minLevel: 4 }] } },
    { id: 'dut-33', title: 'Bachelor of Journalism', requirements: { minAPS: null, requiredSubjects: [{ subject: 'english', minLevel: 5 }] } },
    { id: 'dut-34', title: 'Diploma in Drama', requirements: { minAPS: 24, requiredSubjects: [{ subject: 'english', minLevel: 4 }] } },
    { id: 'dut-35', title: 'Diploma in Fashion Design', requirements: { minAPS: null, requiredSubjects: [{ subject: 'english', minLevel: 3 }] } },
    { id: 'dut-36', title: 'Diploma in Fine Art', requirements: { minAPS: null, requiredSubjects: [{ subject: 'english', minLevel: 3 }] } },
    { id: 'dut-37', title: 'Diploma in Interior Design', requirements: { minAPS: null, requiredSubjects: [{ subject: 'english', minLevel: 3 }] } },
    { id: 'dut-38', title: 'Diploma in Jewellery Design and Manufacture', requirements: { minAPS: null, requiredSubjects: [{ subject: 'english', minLevel: 3 }] } },
    { id: 'dut-39', title: 'Diploma in Language Practice', requirements: { minAPS: null, requiredSubjects: [{ subject: 'english', minLevel: 4 }] } },
    { id: 'dut-40', title: 'Higher Certificate: Performing Arts Technology', requirements: { minAPS: null, requiredSubjects: [{ subject: 'english', minLevel: 3 }] } },

    // Faculty of Engineering and Built Environment
    { id: 'dut-41', title: 'Bachelor Built Environment: Urban and Regional Planning', requirements: { minAPS: null, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'mathematics', minLevel: 4 }] } },
    { id: 'dut-42', title: 'Bachelor of Engineering Technology in Chemical Engineering', requirements: { minAPS: null, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'mathematics', minLevel: 4 }, { subject: 'physical_sciences', minLevel: 4 }] } },
    { id: 'dut-43', title: 'Bachelor of Engineering Technology in Electronic Engineering', requirements: { minAPS: null, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'mathematics', minLevel: 4 }, { subject: 'physical_sciences', minLevel: 4 }] } },
    { id: 'dut-44', title: 'Bachelor of Engineering Technology in Industrial Engineering', requirements: { minAPS: null, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'mathematics', minLevel: 4 }, { subject: 'physical_sciences', minLevel: 4 }] } },
    { id: 'dut-45', title: 'Bachelor of Engineering Technology in Mechanical Engineering', requirements: { minAPS: null, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'mathematics', minLevel: 4 }, { subject: 'physical_sciences', minLevel: 4 }] } },
    { id: 'dut-46', title: 'Bachelor of Engineering Technology in Power Engineering', requirements: { minAPS: null, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'mathematics', minLevel: 4 }, { subject: 'physical_sciences', minLevel: 4 }] } },
    { id: 'dut-47', title: 'Bachelor of the Built Environment in Architecture', requirements: { minAPS: null, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'mathematics', minLevel: 4 }] } },
    { id: 'dut-48', title: 'Bachelor of the Built Environment in Construction Studies', requirements: { minAPS: null, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'mathematics', minLevel: 4 }, { subject: 'physical_sciences', minLevel: 4 }] } },
    { id: 'dut-49', title: 'Bachelor of the Built Environment in Geomatics', requirements: { minAPS: null, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'mathematics', minLevel: 4 }, { subject: 'physical_sciences', minLevel: 4 }] } },
    { id: 'dut-50', title: 'Bachelor of Engineering Technology in Civil Engineering', requirements: { minAPS: null, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'mathematics', minLevel: 4 }, { subject: 'physical_sciences', minLevel: 4 }] } },
    { id: 'dut-51', title: 'Diploma in Engineering Technology in Civil Engineering', requirements: { minAPS: null, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'mathematics', minLevel: 4 }, { subject: 'physical_sciences', minLevel: 4 }] } },
    { id: 'dut-52', title: 'Diploma in Built Environment in Construction Studies', requirements: { minAPS: null, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'mathematics', minLevel: 4 }, { subject: 'physical_sciences', minLevel: 4 }] } },
    { id: 'dut-53', title: 'Diploma in Pulp and Paper Technology', requirements: { minAPS: null, requiredSubjects: [{ subject: 'english', minLevel: 3 }, { subject: 'mathematics', minLevel: 4 }, { subject: 'physical_sciences', minLevel: 4 }] } },

    // Faculty of Health Sciences
    { id: 'dut-54', title: 'Bachelor of Child & Youth Care', requirements: { minAPS: null, requiredSubjects: [{ subject: 'english', minLevel: 4 }] } },
    { id: 'dut-55', title: 'Bachelor of Health Sciences in Environmental Health', requirements: { minAPS: null, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'mathematics', minLevel: 4 }, { subject: 'life_sciences', minLevel: 4 }, { subject: 'physical_sciences', minLevel: 4 }] } },
    { id: 'dut-56', title: 'Bachelor of Health Sciences in Radiography: Diagnostic', requirements: { minAPS: 28, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'mathematics', minLevel: 4 }, { subject: 'life_sciences', minLevel: 4 }, { subject: 'physical_sciences', minLevel: 4 }] } },
    { id: 'dut-57', title: 'Bachelor of Health Sciences in Radiography: Sonography', requirements: { minAPS: 28, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'mathematics', minLevel: 4 }, { subject: 'life_sciences', minLevel: 4 }, { subject: 'physical_sciences', minLevel: 4 }] } },
    { id: 'dut-58', title: 'Bachelor of Health Sciences in Radiography: Therapy and Oncology', requirements: { minAPS: 28, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'mathematics', minLevel: 4 }, { subject: 'life_sciences', minLevel: 4 }, { subject: 'physical_sciences', minLevel: 4 }] } },
    { id: 'dut-59', title: 'Bachelor of Health Sciences in Clinical Technology', requirements: { minAPS: null, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'mathematics', minLevel: 4 }, { subject: 'life_sciences', minLevel: 4 }, { subject: 'physical_sciences', minLevel: 4 }] } },
    { id: 'dut-60', title: 'Bachelor of Health Sciences in Emergency Medical Care', requirements: { minAPS: 30, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'mathematics', minLevel: 4 }, { subject: 'life_sciences', minLevel: 4 }, { subject: 'physical_sciences', minLevel: 4 }] } },
    { id: 'dut-61', title: 'Bachelor of Health Sciences in Homeopathy', requirements: { minAPS: null, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'mathematics', minLevel: 4 }, { subject: 'life_sciences', minLevel: 4 }, { subject: 'physical_sciences', minLevel: 4 }] } },
    { id: 'dut-62', title: 'Bachelor of Health Sciences in Chiropractic', requirements: { minAPS: null, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'mathematics', minLevel: 4 }, { subject: 'life_sciences', minLevel: 4 }, { subject: 'physical_sciences', minLevel: 4 }] } },
    { id: 'dut-63', title: 'Bachelor of Health Sciences in Medical Laboratory Science', requirements: { minAPS: null, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'mathematics', minLevel: 4 }, { subject: 'life_sciences', minLevel: 4 }, { subject: 'physical_sciences', minLevel: 4 }] } },
    { id: 'dut-64', title: 'Bachelor in Nursing', requirements: { minAPS: 28, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'life_sciences', minLevel: 4 }, { subject: 'mathematics', minLevel: 4 }] } },
    { id: 'dut-65', title: 'Diploma in Somatology', requirements: { minAPS: null, requiredSubjects: [{ subject: 'english', minLevel: 3 }, { subject: 'life_sciences', minLevel: 4 }, { subject: 'mathematics', minLevel: 3 }] } },
    { id: 'dut-66', title: 'Higher Cert in Dental Assisting', requirements: { minAPS: null, requiredSubjects: [{ subject: 'english', minLevel: 3 }, { subject: 'mathematics', minLevel: 3 }] } },

    // Faculty of Management Sciences
    { id: 'dut-67', title: 'Diploma in Business Administration', requirements: { minAPS: 25, requiredSubjects: [{ subject: 'english', minLevel: 3 }, { subject: 'mathematics', minLevel: 3 }] } },
    { id: 'dut-68', title: 'Diploma in Business Law', requirements: { minAPS: 25, requiredSubjects: [{ subject: 'english', minLevel: 3 }, { subject: 'mathematics', minLevel: 3 }] } },
    { id: 'dut-69', title: 'Diploma in Human Resources', requirements: { minAPS: 25, requiredSubjects: [{ subject: 'english', minLevel: 3 }, { subject: 'mathematics', minLevel: 3 }] } },
    { id: 'dut-70', title: 'Diploma in Marketing', requirements: { minAPS: 25, requiredSubjects: [{ subject: 'english', minLevel: 3 }, { subject: 'mathematics', minLevel: 3 }] } },
    { id: 'dut-71', title: 'Diploma in Operations', requirements: { minAPS: 25, requiredSubjects: [{ subject: 'english', minLevel: 3 }, { subject: 'mathematics', minLevel: 3 }] } },
    { id: 'dut-72', title: 'Diploma in Public Relations & Communication Management', requirements: { minAPS: 25, requiredSubjects: [{ subject: 'english', minLevel: 3 }, { subject: 'mathematics', minLevel: 3 }] } },
    { id: 'dut-73', title: 'Diploma in Retail', requirements: { minAPS: 25, requiredSubjects: [{ subject: 'english', minLevel: 3 }, { subject: 'mathematics', minLevel: 3 }] } },
    { id: 'dut-74', title: 'Diploma in Public Administration: Disaster & Risk Management', requirements: { minAPS: 25, requiredSubjects: [{ subject: 'english', minLevel: 3 }, { subject: 'mathematics', minLevel: 3 }] } },
    { id: 'dut-75', title: 'Diploma in Public Administration: Local Government', requirements: { minAPS: 25, requiredSubjects: [{ subject: 'english', minLevel: 3 }, { subject: 'mathematics', minLevel: 3 }] } },
    { id: 'dut-76', title: 'Diploma in Public Administration: Public Management', requirements: { minAPS: 25, requiredSubjects: [{ subject: 'english', minLevel: 3 }, { subject: 'mathematics', minLevel: 3 }] } },
    { id: 'dut-77', title: 'Diploma in Public Administration: Supply Chain Management', requirements: { minAPS: 25, requiredSubjects: [{ subject: 'english', minLevel: 3 }, { subject: 'mathematics', minLevel: 3 }] } },
    { id: 'dut-78', title: 'Diploma in Catering Management', requirements: { minAPS: null, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'mathematics', minLevel: 2 }] } },
    { id: 'dut-79', title: 'Diploma in Hospitality Management', requirements: { minAPS: null, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'mathematics', minLevel: 2 }] } },
    { id: 'dut-80', title: 'Diploma in Tourism Management', requirements: { minAPS: 26, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'mathematics', minLevel: 2 }] } },
    { id: 'dut-81', title: 'Diploma in Eco Tourism', requirements: { minAPS: 25, requiredSubjects: [{ subject: 'english', minLevel: 3 }, { subject: 'mathematics', minLevel: 3 }] } }
];