export const coursesVUT = [
    // Faculty of Applied & Computer Sciences
    { id: 'vut-1', title: 'Diploma: Analytical Chemistry (3 years)', requirements: { minAPS: 21, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'mathematics', minLevel: 4 }, { subject: 'technical_mathematics', minLevel: 4 }, { subject: 'physical_sciences', minLevel: 4 }] } },
    { id: 'vut-2', title: 'Diploma: Agricultural Management (3 years) - Mathematics Stream', requirements: { minAPS: 21, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'mathematics', minLevel: 3 }, { subject: 'technical_mathematics', minLevel: 3 }, { subject: 'agriculture', minLevel: 3 }, { subject: 'life_sciences', minLevel: 3 }] } },
    { id: 'vut-3', title: 'Diploma: Agricultural Management (3 years) - Mathematical Literacy Stream', requirements: { minAPS: 22, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'mathematical_literacy', minLevel: 4 }, { subject: 'agriculture', minLevel: 3 }, { subject: 'life_sciences', minLevel: 3 }] } },
    { id: 'vut-4', title: 'Diploma: Biotechnology (3 years)', requirements: { minAPS: 23, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'mathematics', minLevel: 4 }, { subject: 'physical_sciences', minLevel: 4 }, { subject: 'life_sciences', minLevel: 4 }] } },
    { id: 'vut-5', title: 'Diploma: Non-Destructive Testing', requirements: { minAPS: 19, requiredSubjects: [{ subject: 'english', minLevel: 3 }, { subject: 'mathematics', minLevel: 3 }, { subject: 'technical_mathematics', minLevel: 3 }, { subject: 'physical_sciences', minLevel: 4 }, { subject: 'technical_science', minLevel: 4 }] } },
    { id: 'vut-6', title: 'Diploma: Information Technology (3 years) - Mathematics Stream', requirements: { minAPS: 26, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'mathematics', minLevel: 4 }, { subject: 'technical_mathematics', minLevel: 4 }] } },
    { id: 'vut-7', title: 'Diploma: Information Technology (3 years) - Mathematical Literacy Stream', requirements: { minAPS: 28, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'mathematical_literacy', minLevel: 6 }] } },
    { id: 'vut-8', title: 'Diploma: Environmental Science (3 years)', requirements: { minAPS: 21, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'mathematics', minLevel: 4 }, { subject: 'physical_sciences', minLevel: 4 }] } },
    { id: 'vut-9', title: 'Extended Information Technology Programme - Mathematics Stream', requirements: { minAPS: 24, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'mathematics', minLevel: 4 }, { subject: 'technical_mathematics', minLevel: 4 }] } },
    { id: 'vut-10', title: 'Extended Information Technology Programme - Mathematical Literacy Stream', requirements: { minAPS: 26, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'mathematical_literacy', minLevel: 6 }] } },
    { id: 'vut-11', title: 'Bachelor of Health Sciences: Medical Laboratory Science (4 years)', requirements: { minAPS: 27, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'mathematics', minLevel: 4 }, { subject: 'physical_sciences', minLevel: 4 }, { subject: 'life_sciences', minLevel: 5 }] } },

    // Faculty of Management Sciences - Accountancy
    { id: 'vut-12', title: 'Diploma: Financial Information Systems', requirements: { minAPS: 20, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'accounting', minLevel: 4 }, { subject: 'mathematics', minLevel: 3 }, { subject: 'technical_mathematics', minLevel: 3 }, { subject: 'mathematical_literacy', minLevel: 5 }] } },
    { id: 'vut-13', title: 'Diploma: Cost & Management Accounting', requirements: { minAPS: 20, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'accounting', minLevel: 4 }, { subject: 'mathematics', minLevel: 3 }, { subject: 'technical_mathematics', minLevel: 3 }, { subject: 'mathematical_literacy', minLevel: 5 }] } },
    { id: 'vut-14', title: 'Diploma: Internal Auditing', requirements: { minAPS: 20, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'accounting', minLevel: 4 }, { subject: 'mathematics', minLevel: 3 }, { subject: 'technical_mathematics', minLevel: 3 }, { subject: 'mathematical_literacy', minLevel: 6 }] } },

    // Faculty of Management Sciences - Other Departments
    { id: 'vut-15', title: 'Diploma: Human Resources Management', requirements: { minAPS: 20, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'mathematics', minLevel: 3 }, { subject: 'technical_mathematics', minLevel: 3 }, { subject: 'mathematical_literacy', minLevel: 4 }] } },
    { id: 'vut-16', title: 'Diploma: Logistics and Supply Chain Management', requirements: { minAPS: 20, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'mathematics', minLevel: 3 }, { subject: 'technical_mathematics', minLevel: 3 }, { subject: 'mathematical_literacy', minLevel: 4 }] } },
    { id: 'vut-17', title: 'Diploma: Marketing', requirements: { minAPS: 20, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'mathematics', minLevel: 3 }, { subject: 'technical_mathematics', minLevel: 3 }, { subject: 'mathematical_literacy', minLevel: 4 }] } },
    { id: 'vut-18', title: 'Diploma: Retail Business Management', requirements: { minAPS: 20, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'mathematics', minLevel: 3 }, { subject: 'technical_mathematics', minLevel: 3 }, { subject: 'mathematical_literacy', minLevel: 4 }] } },
    { id: 'vut-19', title: 'Diploma: Sport Management', requirements: { minAPS: 20, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'mathematics', minLevel: 3 }, { subject: 'technical_mathematics', minLevel: 3 }, { subject: 'mathematical_literacy', minLevel: 4 }] } },

    // Faculty of Human Sciences
    { id: 'vut-20', title: 'Diploma: Fashion, Photography, Graphic Design & Fine Art - Mathematics Stream', requirements: { minAPS: 21, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'mathematics', minLevel: 2 }, { subject: 'technical_mathematics', minLevel: 2 }] } },
    { id: 'vut-21', title: 'Diploma: Fashion, Photography, Graphic Design & Fine Art - Mathematical Literacy Stream', requirements: { minAPS: 22, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'mathematical_literacy', minLevel: 3 }] } },
    { id: 'vut-22', title: 'Diploma: Food Service Management - Mathematics Stream', requirements: { minAPS: 20, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'mathematics', minLevel: 3 }, { subject: 'technical_mathematics', minLevel: 3 }] } },
    { id: 'vut-23', title: 'Diploma: Food Service Management - Mathematical Literacy Stream', requirements: { minAPS: 21, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'mathematical_literacy', minLevel: 4 }] } },
    { id: 'vut-24', title: 'Diploma: Public Relations - Mathematics Stream', requirements: { minAPS: 20, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'mathematics', minLevel: 3 }, { subject: 'technical_mathematics', minLevel: 3 }] } },
    { id: 'vut-25', title: 'Diploma: Public Relations - Mathematical Literacy Stream', requirements: { minAPS: 21, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'mathematical_literacy', minLevel: 4 }] } },
    { id: 'vut-26', title: 'Diploma: Tourism Management - Mathematics Stream', requirements: { minAPS: 20, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'mathematics', minLevel: 3 }, { subject: 'technical_mathematics', minLevel: 3 }] } },
    { id: 'vut-27', title: 'Diploma: Tourism Management - Mathematical Literacy Stream', requirements: { minAPS: 21, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'mathematical_literacy', minLevel: 4 }] } },
    { id: 'vut-28', title: 'Diploma: Ecotourism Management - Mathematics Stream', requirements: { minAPS: 20, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'biology', minLevel: 4 }, { subject: 'life_sciences', minLevel: 4 }, { subject: 'mathematics', minLevel: 3 }, { subject: 'technical_mathematics', minLevel: 3 }] } },
    { id: 'vut-29', title: 'Diploma: Ecotourism Management - Mathematical Literacy Stream', requirements: { minAPS: 21, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'biology', minLevel: 4 }, { subject: 'life_sciences', minLevel: 4 }, { subject: 'mathematical_literacy', minLevel: 4 }] } },
    { id: 'vut-30', title: 'Diploma: Labour Law - Mathematics Stream', requirements: { minAPS: 23, requiredSubjects: [{ subject: 'english', minLevel: 5 }, { subject: 'other_language', minLevel: 3 }, { subject: 'mathematics', minLevel: 3 }, { subject: 'technical_mathematics', minLevel: 3 }] } },
    { id: 'vut-31', title: 'Diploma: Labour Law - Mathematical Literacy Stream', requirements: { minAPS: 24, requiredSubjects: [{ subject: 'english', minLevel: 5 }, { subject: 'other_language', minLevel: 3 }, { subject: 'mathematical_literacy', minLevel: 4 }] } },
    { id: 'vut-32', title: 'Diploma: Legal Assistance - Mathematics Stream', requirements: { minAPS: 21, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'mathematics', minLevel: 3 }, { subject: 'technical_mathematics', minLevel: 3 }] } },
    { id: 'vut-33', title: 'Diploma: Legal Assistance - Mathematical Literacy Stream', requirements: { minAPS: 22, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'mathematical_literacy', minLevel: 4 }] } },
    { id: 'vut-34', title: 'Diploma: Safety Management - Mathematics Stream', requirements: { minAPS: 20, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'other_language', minLevel: 3 }, { subject: 'mathematics', minLevel: 3 }, { subject: 'technical_mathematics', minLevel: 3 }] } },
    { id: 'vut-35', title: 'Diploma: Safety Management - Mathematical Literacy Stream', requirements: { minAPS: 21, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'other_language', minLevel: 3 }, { subject: 'mathematical_literacy', minLevel: 4 }] } },
    { id: 'vut-36', title: 'Diploma: Policing - Mathematics Stream', requirements: { minAPS: 20, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'mathematics', minLevel: 3 }, { subject: 'technical_mathematics', minLevel: 3 }] } },
    { id: 'vut-37', title: 'Diploma: Policing - Mathematical Literacy Stream', requirements: { minAPS: 21, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'mathematical_literacy', minLevel: 4 }] } },
    { id: 'vut-38', title: 'Bachelor of Education (Senior Phase & FET Teaching) - Mathematics Stream', requirements: { minAPS: 22, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'mathematics', minLevel: 4 }, { subject: 'technical_mathematics', minLevel: 4 }, { subject: 'physical_sciences', minLevel: 3 }, { subject: 'technical_science', minLevel: 3 }] } },
    { id: 'vut-39', title: 'Bachelor of Education (Senior Phase & FET Teaching) - Mathematical Literacy Stream', requirements: { minAPS: 24, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'mathematical_literacy', minLevel: 6 }, { subject: 'physical_sciences', minLevel: 3 }, { subject: 'technical_science', minLevel: 3 }] } },
    { id: 'vut-40', title: 'Bachelor of Communication Studies - Mathematics Stream', requirements: { minAPS: 20, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'mathematics', minLevel: 3 }, { subject: 'technical_mathematics', minLevel: 3 }, { subject: 'other_language', minLevel: 4 }] } },
    { id: 'vut-41', title: 'Bachelor of Communication Studies - Mathematical Literacy Stream', requirements: { minAPS: 21, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'mathematical_literacy', minLevel: 4 }, { subject: 'other_language', minLevel: 4 }] } },

    // Faculty of Engineering & Technology - Mainstream (3 years)
    { id: 'vut-42', title: 'Diploma: Chemical Engineering (3 years)', requirements: { minAPS: 24, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'mathematics', minLevel: 4 }, { subject: 'physical_sciences', minLevel: 4 }] } },
    { id: 'vut-43', title: 'Diploma: Civil Engineering (3 years)', requirements: { minAPS: 24, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'mathematics', minLevel: 4 }, { subject: 'physical_sciences', minLevel: 4 }] } },
    { id: 'vut-44', title: 'Diploma: Industrial Engineering (3 years)', requirements: { minAPS: 24, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'mathematics', minLevel: 4 }, { subject: 'physical_sciences', minLevel: 4 }] } },
    { id: 'vut-45', title: 'Diploma: Mechanical Engineering (3 years)', requirements: { minAPS: 24, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'mathematics', minLevel: 4 }, { subject: 'physical_sciences', minLevel: 4 }] } },
    { id: 'vut-46', title: 'Diploma: Metallurgical Engineering (3 years)', requirements: { minAPS: 24, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'mathematics', minLevel: 4 }, { subject: 'physical_sciences', minLevel: 4 }] } },
    { id: 'vut-47', title: 'Diploma: Electronic Engineering (3 years)', requirements: { minAPS: 24, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'mathematics', minLevel: 4 }, { subject: 'physical_sciences', minLevel: 4 }] } },
    { id: 'vut-48', title: 'Diploma: Power Engineering (3 years)', requirements: { minAPS: 24, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'mathematics', minLevel: 4 }, { subject: 'physical_sciences', minLevel: 4 }] } },
    { id: 'vut-49', title: 'Diploma: Process Control Engineering (3 years)', requirements: { minAPS: 24, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'mathematics', minLevel: 4 }, { subject: 'physical_sciences', minLevel: 4 }] } },
    { id: 'vut-50', title: 'Diploma: Computer Systems Engineering (3 years)', requirements: { minAPS: 24, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'mathematics', minLevel: 4 }, { subject: 'physical_sciences', minLevel: 4 }] } },

    // Faculty of Engineering & Technology - Extended (4 years)
    { id: 'vut-51', title: 'Diploma: Chemical Engineering (Extended - 4 years)', requirements: { minAPS: 22, requiredSubjects: [{ subject: 'english', minLevel: 3 }, { subject: 'mathematics', minLevel: 3 }, { subject: 'physical_sciences', minLevel: 3 }] } },
    { id: 'vut-52', title: 'Diploma: Civil Engineering (Extended - 4 years)', requirements: { minAPS: 22, requiredSubjects: [{ subject: 'english', minLevel: 3 }, { subject: 'mathematics', minLevel: 3 }, { subject: 'physical_sciences', minLevel: 3 }] } },
    { id: 'vut-53', title: 'Diploma: Industrial Engineering (Extended - 4 years)', requirements: { minAPS: 22, requiredSubjects: [{ subject: 'english', minLevel: 3 }, { subject: 'mathematics', minLevel: 3 }, { subject: 'physical_sciences', minLevel: 3 }] } },
    { id: 'vut-54', title: 'Diploma: Mechanical Engineering (Extended - 4 years)', requirements: { minAPS: 22, requiredSubjects: [{ subject: 'english', minLevel: 3 }, { subject: 'mathematics', minLevel: 3 }, { subject: 'physical_sciences', minLevel: 3 }] } },
    { id: 'vut-55', title: 'Diploma: Metallurgical Engineering (Extended - 4 years)', requirements: { minAPS: 22, requiredSubjects: [{ subject: 'english', minLevel: 3 }, { subject: 'mathematics', minLevel: 3 }, { subject: 'physical_sciences', minLevel: 3 }] } },
    { id: 'vut-56', title: 'Diploma: Electronic Engineering (Extended - 4 years)', requirements: { minAPS: 22, requiredSubjects: [{ subject: 'english', minLevel: 3 }, { subject: 'mathematics', minLevel: 3 }, { subject: 'physical_sciences', minLevel: 3 }] } },
    { id: 'vut-57', title: 'Diploma: Power Engineering (Extended - 4 years)', requirements: { minAPS: 22, requiredSubjects: [{ subject: 'english', minLevel: 3 }, { subject: 'mathematics', minLevel: 3 }, { subject: 'physical_sciences', minLevel: 3 }] } },
    { id: 'vut-58', title: 'Diploma: Process Control Engineering (Extended - 4 years)', requirements: { minAPS: 22, requiredSubjects: [{ subject: 'english', minLevel: 3 }, { subject: 'mathematics', minLevel: 3 }, { subject: 'physical_sciences', minLevel: 3 }] } },
    { id: 'vut-59', title: 'Diploma: Computer Systems Engineering (Extended - 4 years)', requirements: { minAPS: 22, requiredSubjects: [{ subject: 'english', minLevel: 3 }, { subject: 'mathematics', minLevel: 3 }, { subject: 'physical_sciences', minLevel: 3 }] } },

    // Faculty of Engineering & Technology - Operations Management
    { id: 'vut-60', title: 'Diploma: Operations Management (3 years)', requirements: { minAPS: 23, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'mathematics', minLevel: 4 }, { subject: 'physical_sciences', minLevel: 3 }] } }
];