export const coursesWITS = [
    // Faculty of Commerce, Law & Management
    { id: '147', title: 'Bachelor of Commerce (BCom) - General', requirements: { minAPS: 38, requiredSubjects: [{ subject: 'english', minLevel: 5 }, { subject: 'mathematics', minLevel: 5 }] } },
    { id: '148', title: 'Bachelor of Commerce (BCom) - Information Systems', requirements: { minAPS: 38, requiredSubjects: [{ subject: 'english', minLevel: 5 }, { subject: 'mathematics', minLevel: 5 }] } },
    { id: '149', title: 'Bachelor of Commerce (BCom) - Politics, Philosophy and Economics', requirements: { minAPS: 38, requiredSubjects: [{ subject: 'english', minLevel: 5 }, { subject: 'mathematics', minLevel: 5 }] } },
    { id: '150', title: 'Bachelor of Accounting Science', requirements: { minAPS: 44, requiredSubjects: [{ subject: 'english', minLevel: 5 }, { subject: 'mathematics', minLevel: 6 }] } },
    { id: '151', title: 'Bachelor of Accounting', requirements: { minAPS: 38, requiredSubjects: [{ subject: 'english', minLevel: 5 }, { subject: 'mathematics', minLevel: 5 }] } },
    { id: '152', title: 'Bachelor of Economic Science', requirements: { minAPS: 42, requiredSubjects: [{ subject: 'english', minLevel: 5 }, { subject: 'mathematics', minLevel: 7 }] } },
    { id: '153', title: 'Bachelor of Commerce with Law', requirements: { minAPS: 43, requiredSubjects: [{ subject: 'english', minLevel: 5 }, { subject: 'mathematics', minLevel: 5 }] } },
    { id: '154', title: 'Bachelor of Laws (LLB) - Four-Year Stream', requirements: { minAPS: 46, requiredSubjects: [{ subject: 'english', minLevel: 6 }, { subject: 'mathematics', minLevel: 4 }, { subject: 'mathematical_literacy', minLevel: 6 }] } },

    // Faculty of Engineering and the Built Environment
    { id: '155', title: 'Bachelor of Engineering (BEng) - Chemical Engineering', requirements: { minAPS: 42, requiredSubjects: [{ subject: 'english', minLevel: 5 }, { subject: 'mathematics', minLevel: 5 }, { subject: 'physical_sciences', minLevel: 5 }] } },
    { id: '156', title: 'Bachelor of Engineering (BEng) - Metallurgy and Materials Engineering', requirements: { minAPS: 42, requiredSubjects: [{ subject: 'english', minLevel: 5 }, { subject: 'mathematics', minLevel: 5 }, { subject: 'physical_sciences', minLevel: 5 }] } },
    { id: '157', title: 'Bachelor of Engineering (BEng) - Civil Engineering', requirements: { minAPS: 42, requiredSubjects: [{ subject: 'english', minLevel: 5 }, { subject: 'mathematics', minLevel: 5 }, { subject: 'physical_sciences', minLevel: 5 }] } },
    { id: '158', title: 'Bachelor of Engineering (BEng) - Electrical Engineering', requirements: { minAPS: 42, requiredSubjects: [{ subject: 'english', minLevel: 5 }, { subject: 'mathematics', minLevel: 5 }, { subject: 'physical_sciences', minLevel: 5 }] } },
    { id: '159', title: 'Bachelor of Engineering (BEng) - Biomedical Engineering', requirements: { minAPS: 42, requiredSubjects: [{ subject: 'english', minLevel: 5 }, { subject: 'mathematics', minLevel: 5 }, { subject: 'physical_sciences', minLevel: 5 }] } },
    { id: '160', title: 'Bachelor of Engineering (BEng) - Digital Arts', requirements: { minAPS: 42, requiredSubjects: [{ subject: 'english', minLevel: 5 }, { subject: 'mathematics', minLevel: 5 }, { subject: 'physical_sciences', minLevel: 5 }] } },
    { id: '161', title: 'Bachelor of Engineering (BEng) - Aeronautical Engineering', requirements: { minAPS: 42, requiredSubjects: [{ subject: 'english', minLevel: 5 }, { subject: 'mathematics', minLevel: 5 }, { subject: 'physical_sciences', minLevel: 5 }] } },
    { id: '162', title: 'Bachelor of Engineering (BEng) - Industrial Engineering', requirements: { minAPS: 42, requiredSubjects: [{ subject: 'english', minLevel: 5 }, { subject: 'mathematics', minLevel: 5 }, { subject: 'physical_sciences', minLevel: 5 }] } },
    { id: '163', title: 'Bachelor of Engineering (BEng) - Mechanical Engineering', requirements: { minAPS: 42, requiredSubjects: [{ subject: 'english', minLevel: 5 }, { subject: 'mathematics', minLevel: 5 }, { subject: 'physical_sciences', minLevel: 5 }] } },
    { id: '164', title: 'Bachelor of Engineering (BEng) - Mining Engineering', requirements: { minAPS: 42, requiredSubjects: [{ subject: 'english', minLevel: 5 }, { subject: 'mathematics', minLevel: 5 }, { subject: 'physical_sciences', minLevel: 5 }] } },
    { id: '165', title: 'Bachelor of Architectural Studies', requirements: { minAPS: 34, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'mathematics', minLevel: 4 }] } },
    { id: '166', title: 'Bachelor of Urban and Regional Planning', requirements: { minAPS: 36, requiredSubjects: [{ subject: 'english', minLevel: 5 }, { subject: 'mathematics', minLevel: 5 }] } },
    { id: '167', title: 'Bachelor of Construction Studies', requirements: { minAPS: 36, requiredSubjects: [{ subject: 'english', minLevel: 5 }, { subject: 'mathematics', minLevel: 5 }] } },
    { id: '168', title: 'Bachelor of Property Studies', requirements: { minAPS: 36, requiredSubjects: [{ subject: 'english', minLevel: 5 }, { subject: 'mathematics', minLevel: 5 }] } },

    // Faculty of Health Sciences
    { id: '169', title: 'Bachelor of Biomedical Sciences', requirements: { minAPS: 0, requiredSubjects: [{ subject: 'english', minLevel: 5 }, { subject: 'mathematics', minLevel: 5 }, { subject: 'life_sciences', minLevel: 5 }] } },
    { id: '170', title: 'Bachelor of Biokinetics', requirements: { minAPS: 0, requiredSubjects: [{ subject: 'english', minLevel: 5 }, { subject: 'mathematics', minLevel: 5 }, { subject: 'life_sciences', minLevel: 5 }] } },
    { id: '171', title: 'Bachelor of Health Systems Sciences - Clinical Medical Practice', requirements: { minAPS: 7, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'mathematics', minLevel: 4 }, { subject: 'life_sciences', minLevel: 4 }, { subject: 'physical_sciences', minLevel: 4 }] } },
    { id: '172', title: 'Bachelor of Medicine and Surgery (MBChB)', requirements: { minAPS: 0, requiredSubjects: [{ subject: 'english', minLevel: 5 }, { subject: 'mathematics', minLevel: 5 }, { subject: 'life_sciences', minLevel: 5 }, { subject: 'physical_sciences', minLevel: 5 }] } },
    { id: '173', title: 'Bachelor of Dental Science', requirements: { minAPS: 0, requiredSubjects: [{ subject: 'english', minLevel: 5 }, { subject: 'mathematics', minLevel: 5 }, { subject: 'life_sciences', minLevel: 5 }, { subject: 'physical_sciences', minLevel: 5 }] } },
    { id: '174', title: 'Bachelor of Oral Health Sciences', requirements: { minAPS: 0, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'mathematics', minLevel: 4 }, { subject: 'life_sciences', minLevel: 4 }, { subject: 'physical_sciences', minLevel: 4 }] } },
    { id: '175', title: 'Bachelor of Nursing', requirements: { minAPS: 0, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'mathematics', minLevel: 4 }, { subject: 'life_sciences', minLevel: 4 }] } },
    { id: '176', title: 'Bachelor of Pharmacy', requirements: { minAPS: 0, requiredSubjects: [{ subject: 'english', minLevel: 5 }, { subject: 'mathematics', minLevel: 5 }, { subject: 'physical_sciences', minLevel: 5 }] } },
    { id: '177', title: 'Bachelor of Occupational Therapy', requirements: { minAPS: 0, requiredSubjects: [{ subject: 'english', minLevel: 4 }, { subject: 'mathematics', minLevel: 4 }, { subject: 'life_sciences', minLevel: 4 }] } },
    { id: '178', title: 'Bachelor of Physiotherapy', requirements: { minAPS: 0, requiredSubjects: [{ subject: 'english', minLevel: 5 }, { subject: 'mathematics', minLevel: 5 }, { subject: 'life_sciences', minLevel: 5 }] } },

    // Faculty of Humanities
    { id: '179', title: 'Bachelor of Arts (BA)', requirements: { minAPS: 36, requiredSubjects: [{ subject: 'english', minLevel: 5 }] } },
    { id: '180', title: 'Bachelor of Arts (BA) with Law', requirements: { minAPS: 43, requiredSubjects: [{ subject: 'english', minLevel: 5 }, { subject: 'mathematics', minLevel: 3 }, { subject: 'mathematical_literacy', minLevel: 4 }, { subject: 'technical_mathematics', minLevel: 4 }] } },
    { id: '181', title: 'Bachelor of Arts in Digital Arts', requirements: { minAPS: 36, requiredSubjects: [{ subject: 'english', minLevel: 5 }] } },
    { id: '182', title: 'Bachelor of Arts in Theatre and Performance', requirements: { minAPS: 34, requiredSubjects: [{ subject: 'english', minLevel: 5 }] } },
    { id: '183', title: 'Bachelor of Arts in Film and Television', requirements: { minAPS: 34, requiredSubjects: [{ subject: 'english', minLevel: 5 }] } },
    { id: '184', title: 'Bachelor of Arts in Fine Arts', requirements: { minAPS: 34, requiredSubjects: [{ subject: 'english', minLevel: 5 }] } },
    { id: '185', title: 'Bachelor of Music', requirements: { minAPS: 34, requiredSubjects: [{ subject: 'english', minLevel: 5 }] } },
    { id: '186', title: 'Bachelor of Education (BEd) - Foundation Phase Teaching', requirements: { minAPS: 37, requiredSubjects: [{ subject: 'english', minLevel: 5 }, { subject: 'mathematics', minLevel: 4 }, { subject: 'mathematical_literacy', minLevel: 5 }, { subject: 'technical_mathematics', minLevel: 5 }] } },
    { id: '187', title: 'Bachelor of Education (BEd) - Intermediate Phase Teaching', requirements: { minAPS: 37, requiredSubjects: [{ subject: 'english', minLevel: 5 }, { subject: 'mathematics', minLevel: 4 }, { subject: 'mathematical_literacy', minLevel: 5 }, { subject: 'technical_mathematics', minLevel: 5 }] } },
    { id: '188', title: 'Bachelor of Education (BEd) - Senior Phase and Further Education and Training Teaching', requirements: { minAPS: 37, requiredSubjects: [{ subject: 'english', minLevel: 5 }, { subject: 'mathematics', minLevel: 4 }, { subject: 'mathematical_literacy', minLevel: 5 }, { subject: 'technical_mathematics', minLevel: 5 }] } },
    { id: '189', title: 'Bachelor of Speech-Language Pathology', requirements: { minAPS: 34, requiredSubjects: [{ subject: 'english', minLevel: 5 }, { subject: 'mathematics', minLevel: 4 }] } },
    { id: '190', title: 'Bachelor of Audiology', requirements: { minAPS: 34, requiredSubjects: [{ subject: 'english', minLevel: 5 }, { subject: 'mathematics', minLevel: 4 }] } },
    { id: '191', title: 'Bachelor of Social Work', requirements: { minAPS: 34, requiredSubjects: [{ subject: 'english', minLevel: 5 }] } },

    // Faculty of Science
    { id: '192', title: 'Bachelor of Science (BSc) - General', requirements: { minAPS: 42, requiredSubjects: [{ subject: 'english', minLevel: 5 }, { subject: 'mathematics', minLevel: 5 }, { subject: 'physical_sciences', minLevel: 5 }] } },
    { id: '193', title: 'Bachelor of Science (BSc) - Biological Sciences', requirements: { minAPS: 43, requiredSubjects: [{ subject: 'english', minLevel: 5 }, { subject: 'mathematics', minLevel: 5 }, { subject: 'life_sciences', minLevel: 5 }] } },
    { id: '194', title: 'Bachelor of Science (BSc) - Geographical and Archaeological Sciences', requirements: { minAPS: 42, requiredSubjects: [{ subject: 'english', minLevel: 5 }, { subject: 'mathematics', minLevel: 5 }, { subject: 'physical_sciences', minLevel: 5 }] } },
    { id: '195', title: 'Bachelor of Science (BSc) - Geospatial Sciences', requirements: { minAPS: 42, requiredSubjects: [{ subject: 'english', minLevel: 5 }, { subject: 'mathematics', minLevel: 5 }, { subject: 'physical_sciences', minLevel: 5 }] } },
    { id: '196', title: 'Bachelor of Science (BSc) - Environmental Studies', requirements: { minAPS: 42, requiredSubjects: [{ subject: 'english', minLevel: 5 }, { subject: 'mathematics', minLevel: 5 }, { subject: 'physical_sciences', minLevel: 5 }] } },
    { id: '197', title: 'Bachelor of Science (BSc) - Geological Sciences', requirements: { minAPS: 42, requiredSubjects: [{ subject: 'english', minLevel: 5 }, { subject: 'mathematics', minLevel: 6 }, { subject: 'physical_sciences', minLevel: 5 }] } },
    { id: '198', title: 'Bachelor of Science (BSc) - Actuarial Science', requirements: { minAPS: 42, requiredSubjects: [{ subject: 'english', minLevel: 7 }, { subject: 'mathematics', minLevel: 7 }, { subject: 'physical_sciences', minLevel: 7 }] } },
    { id: '199', title: 'Bachelor of Science (BSc) - Computational and Applied Mathematics', requirements: { minAPS: 44, requiredSubjects: [{ subject: 'english', minLevel: 5 }, { subject: 'mathematics', minLevel: 6 }, { subject: 'physical_sciences', minLevel: 5 }] } },
    { id: '200', title: 'Bachelor of Science (BSc) - Computer Science', requirements: { minAPS: 44, requiredSubjects: [{ subject: 'english', minLevel: 5 }, { subject: 'mathematics', minLevel: 6 }, { subject: 'physical_sciences', minLevel: 5 }] } },
    { id: '201', title: 'Bachelor of Science (BSc) - Mathematical Sciences', requirements: { minAPS: 42, requiredSubjects: [{ subject: 'english', minLevel: 7 }, { subject: 'mathematics', minLevel: 7 }, { subject: 'physical_sciences', minLevel: 7 }] } },
    { id: '202', title: 'Bachelor of Science (BSc) - Physical Sciences (Chemistry/Physics)', requirements: { minAPS: 42, requiredSubjects: [{ subject: 'english', minLevel: 5 }, { subject: 'mathematics', minLevel: 6 }, { subject: 'physical_sciences', minLevel: 5 }] } },
    { id: '203', title: 'Bachelor of Science (BSc) - Chemistry with Chemical Engineering', requirements: { minAPS: 43, requiredSubjects: [{ subject: 'english', minLevel: 5 }, { subject: 'mathematics', minLevel: 6 }, { subject: 'physical_sciences', minLevel: 6 }] } },
    { id: '204', title: 'Bachelor of Science (BSc) - Materials Science', requirements: { minAPS: 43, requiredSubjects: [{ subject: 'english', minLevel: 5 }, { subject: 'mathematics', minLevel: 6 }, { subject: 'physical_sciences', minLevel: 5 }] } },
    { id: '205', title: 'Bachelor of Science (BSc) - Astronomy and Astrophysics', requirements: { minAPS: 43, requiredSubjects: [{ subject: 'english', minLevel: 5 }, { subject: 'mathematics', minLevel: 6 }, { subject: 'physical_sciences', minLevel: 6 }] } }
];

export const availableSubjects = [
    // Compulsory Subjects
    'home_language',
    'first_additional_language',
    'mathematics',
    'mathematical_literacy',
    'life_orientation',
    'technical_mathematics',
    // Elective Subjects
    'second_additional_language',
    'dance_studies',
    'dramatic_arts',
    'music',
    'visual_arts',
    'design',
    'accounting',
    'business_studies',
    'economics',
    'geography',
    'history',
    'religion_studies',
    'agricultural_sciences',
    'life_sciences',
    'physical_sciences',
    'information_technology',
    'civil_technology',
    'electrical_technology',
    'mechanical_technology',
    'engineering_graphics_design',
    'consumer_studies',
    'hospitality_studies',
    'tourism',
    'computer_applications_technology'
];

export const subjectNames = {
    home_language: 'Home Language',
    first_additional_language: 'First Additional Language',
    mathematics: 'Mathematics',
    mathematical_literacy: 'Mathematical Literacy',
    life_orientation: 'Life Orientation',
    technical_mathematics: 'Technical Mathematics',
    second_additional_language: 'Second Additional Language',
    dance_studies: 'Dance Studies',
    dramatic_arts: 'Dramatic Arts',
    music: 'Music',
    visual_arts: 'Visual Arts',
    design: 'Design',
    accounting: 'Accounting',
    business_studies: 'Business Studies',
    economics: 'Economics',
    geography: 'Geography',
    history: 'History',
    religion_studies: 'Religion Studies',
    agricultural_sciences: 'Agricultural Sciences',
    life_sciences: 'Life Sciences',
    physical_sciences: 'Physical Sciences',
    information_technology: 'Information Technology',
    civil_technology: 'Civil Technology',
    electrical_technology: 'Electrical Technology',
    mechanical_technology: 'Mechanical Technology',
    engineering_graphics_design: 'Engineering Graphics and Design',
    consumer_studies: 'Consumer Studies',
    hospitality_studies: 'Hospitality Studies',
    tourism: 'Tourism',
    computer_applications_technology: 'Computer Applications Technology'
};